### ISSUE TITLE
Dataset Link

### ISSUE THREAD

**Issue by aybora** [Maciullo/DroneDetectionDataset#1]
Can you share your dataset via some other (internationally available) cloud service? 

This cloud provider asks for a subscription with the methods which are unavailable in my country.

**Comment by zanilzanzan** [comment]
The same case applies to me. Google Drive would be a more convenient one, for instance. Thanks in advance!

**Comment by trathpai** [comment]
Nice collection of dataset . Would be nice to get it in an internationally available cloud service. Best!

**Comment by 5a7man** [comment]
Cloud provider is unavailable

**Comment by YamacTan** [comment]
I am having the same problem with folks. The cloud service used charges a fee for each file over 1 MB and payment systems are not valid. Is it possible to share in Google Cloud like as train and test snippets?

**Comment by Maciullo** [comment]
Hi there all, sorry for the late response. I am aware of the problem and I will be transferring entire dataset along with new, high performing models trained within the last few months to a new repository. Before I do that I will need to wrap up my PhD and finish another article on this topic.
I have not realized that the old repository was so problematic and I used it for reasons that are no longer valid. I am sorry for that inconvenience.

**Comment by zanilzanzan** [comment]
@Maciullo, thanks a lot for hearing the voice of data-hungry counter-drone enthusiasts and responding kindly. I was wondering if it is possible to just move the dataset to another accessible cloud services in an earlier date, before updating the whole repository with a full revision. That would be simply great! Good luck with the last bits of the PhD. Cheers!

**Comment by Maciullo** [comment]
@zanilzanzan & all, yeah, this probably is the best approach since I am not quite sure how long will it take to publish this new article... Anyhow I deeply appreciate your interest and enthusiasm so I decided not to keep all of you waiting any longer - I added a mirror of the dataset on google drive. You can find the link in the readme. Good luck with your UAV detection and if you beat my benchmarks please be sure to post your score here so that I may be motivated to work harder :)

**Comment by AlexelBlessed** [comment]
Hi,
has anyone been able to use the trained models?

**Comment by Maciullo** [comment]
Dataset is now available on google cloud.

**Comment by sssimpleboy** [comment]
> Dataset is now available on google cloud.
hi ， thanks for your contribution. But I can't visit other web in China, so could you send the dataset to Baidu network disk ? 
Thank you! 
If you think it is too troublesome， you can choose not to do it.
